### ISSUE TITLE
Minta excel fájl konvertálás után feltöltési hiba

### ISSUE THREAD

**Issue by CatherineReike** [vasvince98/ExcelToXml#1]
Az 10. 24., 13:23-kor emailen küldött minta excelt konvertáltam át, és importáltam volna be a moodle oldalon Moodle XML formaként, és a következő hibát dobta: 

![image](https://user-images.githubusercontent.com/94133260/198006148-b120e136-ae45-4c12-b16b-2f3c89c4fc81.png)
:(

**Comment by vasvince98** [comment]
Temporarily solved
